version: "3.3"
services:
  mts-api:
    restart: always
    image: 'postgres:latest'
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mts-db